### ISSUE TITLE
AudioCueEditor takes a really long time to launch up

### ISSUE THREAD

**Issue by MikoMMM** [LazyBone152/XV2-Tools#39]
For comparison, audio tools like eternity audio tools or foobar2000 with vgmstream take like 2 seconds to launch, while ACE (latest version) takes a whole 10 seconds to launch. and it doesn't matter if you loaded an acb/awb or not, it always takes this long to launch.

**Comment by LazyBone152** [comment]
Interesting... personally I never experienced that long of a load time. Usually between 3-5 seconds.

On a hunch I did some testing and found that with the check for updates on startup option off it was considerably faster. Around 2 seconds or less for the window to appear. 

This is supposed to just be checking in the background while the application loads but clearly its blocking it until its finished checking.

**Comment by LazyBone152** [comment]
Should be fixed now

**Comment by MikoMMM** [comment]
Hmmm, seems that the issue is still prevalent, doesn't matter if you have the "check updates on startup" option checked or not.

**Comment by LazyBone152** [comment]
Even with 0.8.3?

It's a clear improvement on my end. The update function was deadlocking the whole application until it finished... though I guess this could just be a coincidence and your issue is something else. 

The issue can be reopened if that is the case but I honestly dunno what could be causing it.

**Comment by MikoMMM** [comment]
Actually it seemed to fix upon system restart
