### ISSUE TITLE
Audio goes silent when importing or replacing new tracks

### ISSUE THREAD

**Issue by F121Live** [LazyBone152/XV2-Tools#42]
I tried to import tracks for a mobile game called Sonic Runners (which is no longer playable, but we have a custom server going on) but whenever I test it in-game it just goes silent.

The game uses ecrypted hca's, we know the key.
Maybe adding re-encryption could fix this?

game download at sonicrunners.com
ACB and AWB files I tested are "BGM_menu.acb" and "BGM_menu_streamfiles.awb"
can be found here: https://cdn.discordapp.com/attachments/587967279845867520/936577801270751242/Audio.zip

**Comment by F121Live** [comment]
Help would be greatly appreciated as we have source code of this game and are trying to develop new content for, the only thing holding us back at the moment is audio :/.

**Comment by JustScratchCoder** [comment]
In the topic of Sonic Runners`s HCA files:
When encrypting the hca, which is needed to play properly, when setting it to loop, it displays an error.
Also when replacing only one track with ACE, it silents the whole file
![image](https://user-images.githubusercontent.com/85436576/151789608-72a26518-a60c-41aa-8a76-193d75d254b4.png)
![image](https://user-images.githubusercontent.com/85436576/151789667-855163e1-860e-408d-a2b5-d8bce8f036f1.png)

**Comment by LazyBone152** [comment]
I've had no experience with encrypted hca files so far so I wasn't entirely sure how to handle them.

It now looks like it would be fairly simple to implement though. Decrypt upon ACB load, save key somewhere, and then just re-encrypt when saving. Add in a menu somewhere for changing/viewing the ACBs encryption key.

This approach would fix the loop issue too. I run my own setup for setting HCA loops (couldn't figure out how VGAudio loops worked...) which doesn't account for any encryption, so that is why that wont work currently.

**Comment by Crafty-The-Fox** [comment]
i have this same issue execpt it isnt encrypted, its with another game. however the .acb is baked in a UEXP (just remove the file header in hxd and add it back after editing)

**Comment by LazyBone152** [comment]
Can you please test this build out and tell me if the audio now works in game?

It should automatically select the encryption key when adding new tracks, but there is also a encryption key editor in the tool menu where you can manually type them in and give them names.

[ACE.zip](https://github.com/LazyBone152/XV2-Tools/files/8330562/ACE.zip)

**Comment by F121Live** [comment]
Thanks, I'll test this as soon as I get home today!

**Comment by JustScratchCoder** [comment]
![image](https://user-images.githubusercontent.com/85436576/159942109-e40bc095-5f3c-48a7-b51c-56fdcd6d73e4.png)
error when saving.... or maybe i did something wrong

**Comment by JustScratchCoder** [comment]
[ace_log.txt](https://github.com/LazyBone152/XV2-Tools/files/8342496/ace_log.txt)
here is the log file

**Comment by F121Live** [comment]
Hi, the audio is still muted on my end
![imagen](https://user-images.githubusercontent.com/55333985/159960209-e246c689-e085-4dfb-a5ad-6e4ba767a191.png)

**Comment by LazyBone152** [comment]
The save issue should now be fixed, and if I'm right about what the silencing issue is caused by, then the original cues should all now work, but any added ones will be silent. 

[ACE.zip](https://github.com/LazyBone152/XV2-Tools/files/8343526/ACE.zip)

**Comment by F121Live** [comment]
Tested the latest build, it's still muted, if you want to be in more direct contact with me for testing you can add me on Discord _F121_#0220

**Comment by F121Live** [comment]
Update: Tried track replacing with the new encryption key feature, it still mutes the audio :(

**Comment by F121Live** [comment]
Update: Attempting to replace audio using the encryption key still mutes the whole file

**Comment by LazyBone152** [comment]
If no edits are made to the file at all (just load & save), does it still go silent?

**Comment by F121Live** [comment]
I'm sorry for the late response, will try ASAP

**Comment by F121Live** [comment]
Hi, I tried opening and saving and now the file crashes my app somehow xD.

**Comment by JustScratchCoder** [comment]
> If no edits are made to the file at all (just load & save), does it still go silent?

yes

**Comment by F121Live** [comment]
> > If no edits are made to the file at all (just load & save), does it still go silent?
> 
> Just tested, it dosent go silent

You're probably using a different file than the one I linked in the post

**Comment by Crafty-The-Fox** [comment]
> > > If no edits are made to the file at all (just load & save), does it still go silent?
> > 
> > 
> > Just tested, it dosent go silent
> 
> You're probably using a different file than the one I linked in the post

i AM using a different file than the one you linked, but im having the same issue as you. Its for a completely different game.

**Comment by Crafty-The-Fox** [comment]
actually funny thing is that this happenes with a non encrypted acb/awb too, but the thing is that it has streaming awbs

**Comment by F121Live** [comment]
Issue is still present on latest update

**Comment by LazyBone152** [comment]
The silencing issue is really similar to issue #58. I think they may be the same.

I've implemented a possible fix for the issue but it needs testing. Here is the build:
[ACE Test.zip](https://github.com/LazyBone152/XV2-Tools/files/9639331/ACE.Test.zip)

**Comment by F121Live** [comment]
Hi, tried 1.0.0 and the issue is fixed but only when I add it as a .wav file, the moment I add an .hca the file breaks and the game crashes.

Even with the .wav there's a small possibility of the game crashing too.

But it's better than nothing, thank you for your hard work, I'll keep exploring the update.


Additional notes:
It seems that adding cues using the button causes issues, I'd rather copy and paste existing cues to then replace the tracks inside them, no idea why this happens.

**Comment by BonQerss** [comment]
Still having this issue with 1.0.0. Playing P4G and attempting to edit the acb and awb to add new cue files to import custom tracks, but the entirety of BGM is muted. 

Using the button to add new cues mutes the entire track.
Copy and pasting existing cues causes the game to crash upon loading past the intro FMV.

I've attempted both options in various ways and it's always either of those two results. Is anyone having a similar issue?

Here are the files I'm using:
https://www.mediafire.com/file/laehiicqbg1crrg/bgm.7z/file

**Comment by Muruaaki** [comment]
I think I have a similar problem. **The cue I edit**  and  **the new cue I add**  with ACE have no audio.

I am editing a game with mobile and Switch versions; I want to bring the mobile content into the Switch version. 
They have the same versions of acb/awb, (ACB Format/PC Ver.1.30.00 Build)
but the audio cue are different. so I tried copying the specific cue into the Switch version; 

ACE plays the audio, but the game doesn't. I tried renaming 1 to 2 and 2 to 1, but the cue I edited with ACE is still broken.
I edited it back; it will work in the game like the original. But I still cannot create a new workable cue.

I tried AtomEncoder to make a new ACB/AWB with HCA.
It works, and I know the game reading depends on the cue names.
but it's waveform, not sequence. This will miss some audio settings.

This is the original file.
https://www.mediafire.com/file/ubd6od2l4jl9u6l/files.zip/file
