### ISSUE TITLE
XmlTool & XV2 Xml Serializer sort skill_item.idb by IDB_Entry IDs

### ISSUE THREAD

**Issue by Sportiax** [LazyBone152/XV2-Tools#6]
I've done multiple tests with skill_item.idb file using XmlTool & XV2 Serializer, seems when the XML file is dragged into the .exe, it sorts them by IDB_Entry ID, the other IDB files are being sorted correctly by IDB_Entry ID & Type value. Sorting only by IDB entry is most likely the cause of the type values be changed. Example: Feint Crash is a Type 0 (Super Skill) after dragging into XmlTool or Serialzer its type value is changed to Type 2 (Evasive), making the skill disappear in-game. (This actually seems to be random, changing type values of different skills each time)

I've also noticed multiple entries of the same IDB are made when saved with XmlTool or Serializer, one with the edits, another base game entry, this also seems to conflict with not all entries being applied with the edits made.

I'm almost certain it's not caused by any issues on my end, as multiple users have confirmed this issue.

Apologies if this comes off a bit blunt, I don't intend it to be that way. If I'm mistaken about this issue, please let me know.

**Comment by LazyBone152** [comment]
So I looked into this and it turns out the IDB file needed to be sorted by the ID AND Type, which was the cause of the issue. 

It's fixed in the latest commit (not yet included in any releases, however).

**Comment by Sportiax** [comment]
Unfortunately doesn't seem to fix the skill_item.idb, while it's being sorted correctly by ID & Type, multiple entries of the same IDB entries are being created. Type values are also still changing. Example: Some Type 0 entries changing to Type 2 entries. Causing skills to be missing in-game.
Also, when applying edits to all skill_item.idb entries, IDB_Entry ID starts at 15, instead of 0.

**Comment by LazyBone152** [comment]
Now fixed
